apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: grayisgreatpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grayisgreatpipelinesjavascriptdocker 
    spec:
      containers:
        - name: grayisgreatpipelinesjavascriptdocker 
          image: testmyapp.azurecr.io/grayisgreatpipelinesjavascriptdocker
          ports:
          - containerPort: 8080